from enum import Enum
class WorkerState(Enum):
    CONNECTED = "CONNECTED"
    HANDSHAKE_DONE = "HANDSHAKE_DONE"
    TASK_SENT = "TASK_SENT"
    TRAINING = "TRAINING"
    SENDING_RESULT = "SENDING_RESULT"
    RESULT_RECEIVED = "RESULT_RECEIVED"   # <-- ADD THIS
    FAILED = "FAILED"

